name        = "fitpack"
author      = "Federico Perini"
copyright   = "Copyright (c) 2022, Federico Perini" 
license     = "BSD-3"
description = "Modern Fortran FITPACK"
homepage    = "https://github.com/perazz/fitpack"
keywords    = ["curve fitting","spline","interpolation"]

[build]
auto-executables = false
auto-examples    = false
auto-tests       = true

[library]
source-dir  = "src"
include-dir = "src"

[install]
library = true

